apiVersion: v1
kind: Pod
metadata:
  name: flask-application-pod
  labels:
    app: flask-application
spec:
  containers:
  - name: flask-application
    image: gcr.io/api-project-249965614499/flask-application

---

apiVersion: v1
kind: Service
metadata:
  name: flask-application-svc
spec:
  selector:
    app: flask-application
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
