apiVersion: v1
kind: Service
metadata:
  name: flask-application-svc
spec:
  type: LoadBalancer
  selector:
    app: flask-application
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000

